# Generated by Django 5.0.2 on 2024-07-13 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('unidad', models.CharField(blank=True, default='-', max_length=10)),
                ('rango_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rango_min', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Piscinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('ubicacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('nombre', models.CharField(max_length=45)),
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxigeno', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=3)),
                ('salinidad', models.DecimalField(decimal_places=2, max_digits=3)),
                ('piscina', models.ForeignKey(default='Eliminada', on_delete=django.db.models.deletion.SET_DEFAULT, to='index.piscinas')),
            ],
        ),
    ]
