# Generated by Django 5.0.2 on 2024-07-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleados',
            table='empleados',
        ),
    ]
