# Generated by Django 5.0.2 on 2024-07-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_empleados_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='unidad',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
