# Generated by Django 5.0.2 on 2024-07-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_mediciones_fecha_mediciones_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='mediciones',
            name='oxigeno',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='mediciones',
            name='ph',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='mediciones',
            name='salinidad',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
