# Generated by Django 5.0.2 on 2024-07-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_mediciones_piscina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediciones',
            name='oxigeno',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='mediciones',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='mediciones',
            name='salinidad',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='rango_max',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='rango_min',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
